type ROOM_ROLES_CONSTANT = OPTIMIZE_CONTROLLER_ROLE | NEW_COLONY_ROLE;

type OPTIMIZE_CONTROLLER_ROLE = "optimize-controller";
type NEW_COLONY_ROLE = "new-colony";

declare const OPTIMIZE_CONTROLLER_ROLE: OPTIMIZE_CONTROLLER_ROLE;
declare const NEW_COLONY_ROLE: NEW_COLONY_ROLE;
